<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZxYCSWf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZxYCSWf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZxYCSWf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZxYCSWf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZxYCSWf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZxYCSWf',
    'container.build_id' => 'bb618966',
    'container.build_time' => 1645491244,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZxYCSWf');
